# This is a basic workflow to help you get started with Actions

name: Hello, World
on: 
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Say Hello
      run: touch new_file.txt 


