name: Joker
on: 
  push:
    branches:
      - main
  schedule:
    - cron: 15 * * * *
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v2
    - name: install curl
      run: sudo apt-get install curl
    - name: get joke
      run: curl https://v2.jokeapi.dev/joke/Any?contains=programmers | grep -e "setup" -e "delivery" | tr -d "\":," | sed -e s/setup// -e s/delivery// > joke.txt
    - name: run ls
      run: ls -la 
    - name: show joke
      run: cat joke.txt