name: Joker
on: 
  push:
    branches:
      - main
  schedule:
    - cron: 15 * * * *
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: get joke
      run: curl https://v2.jokeapi.dev/joke/Any?contians=programmers 
    - name: show joke
      run: cat joke.txt
