name: Joker
on: 
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: get joke
      run: curl https://v2.jokeapi.dev/joke/Any?contains=programmer
