name: My Schedule
on:
  schedule:
    - cron: '15 * * * *'
  workflow_dispatch:

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: Run scheduled message
        run: echo "This step run every 15 mins"
      - name: Create empty file
        run:
          touch my_new_file.txt
